import type { Metadata } from 'next';
import { Sofia_Sans } from 'next/font/google';
import './globals.css';
import Header from './components/header/header';
import Footer from './components/footer';

const sofiaSans = Sofia_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${sofiaSans.className} antialiased`}>
        <Header />
        <main className='flex-grow'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
